### PR TITLE
Put the bucket name in the host name for Amazon S3.

### PR DESCRIPTION
**Pull request by exarkun**
This is a patch Least Authority Enterprises has been carrying in a fork of txAWS.  Unfortunately there don't seem to be any tests or documentation for the behavior.  Also, I can't find any more details about what error cases this helps avoid.  Also, Least Authority Enterprises hasn't actually _used_ this functionality in a long time and things seem to be working okay.  So possibly this change isn't worth incorporating into txAWS proper.

If someone does figure out that this is a good idea, though, at least here's some code to start with.

### CODE REVIEW

**Comment by exarkun** [comment]
Lacking better understanding of why this is a good idea, closing with no intention to invest further effort.

**Comment by exarkun** [comment]
It's possible the "Challenges with Non–DNS-Compliant Bucket Names" section of http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html points towards the problems that putting bucket names into the host name can _cause_ - but that's the opposite of a justification for this change.

**Comment by mithrandi** [comment]
I think the main reason to use the bucket name as the hostname is to query the right S3 regional endpoint without knowing what it is in advance; if you query the wrong endpoint (eg. US endpoint for an EU bucket), you will receive an HTTP 301 response without a Location: header field (deliberately so).

However…the certificate S3 uses for HTTPS is only valid for "*.s3.amazonaws.com" which means that if your bucket name is DNS style (say, "twistedmatrix.com"), you will attempt make an HTTPS connection to "twistedmatrix.com.s3.amazonaws.com" and the certificate will not be valid according to the normal hostname verification rules.

**Comment by mithrandi** [comment]
Ah, according to http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html you receive a 307 with Location, so my information is either incorrect or out of date. However, for request types other than GET, following redirects will result in transferring a lot of data needlessly in the absence of 100-continue support, as noted at http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTRedirect.html

**Pull request closed without merging**
